# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "ar"
pipeline:
  - name: tokenizer_whitespace
  - name: ner_crf
  - name: intent_featurizer_count_vectors
  - name: intent_classifier_tensorflow_embedding
    intent_tokenization_flag: true
    intent_split_symbol: "_"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: KerasPolicy
    batch_size: 50
    epochs: 200
    max_training_samples: 300
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy
